### ISSUE TITLE
Recycling Hyperballs over pokeballs

### ISSUE THREAD

**Issue by poiuytrezaur** [WooAf/PoGoBoT#10]
When recycling. the bot deletes Hyperballs when pokeballs still take inventory spaces. the bot should focus on deleting pokeballs, then superballs then hyperballs (for higher catch chances)
Same for potions, repels ans stuff

**Comment by WooAf** [comment]
The bot recycle item based on that settings: https://github.com/WooAf/PoGoBoT/blob/c5f8fe827aa1be5287a642843fddf96a42745f71/PokemonGo.RocketAPI.GUI/Settings.cs


I'll make an advanced settings for this soon so you can select what you want to keep.
