### ISSUE TITLE
IV Column hiding

### ISSUE THREAD

**Issue by poiuytrezaur** [WooAf/PoGoBoT#11]
After some time (maybe after an evolving session) the IV column just disapears (cf screenshots)

![793cc2ca-543f-11e6-9e23-3d0b6737459e](https://cloud.githubusercontent.com/assets/3758280/17189367/685765b2-5441-11e6-9b40-e0795aa8f9bb.png)
![untitled](https://cloud.githubusercontent.com/assets/3758280/17189346/5a310b5a-5441-11e6-926a-de6c4ca18cb6.png)

**Comment by WooAf** [comment]
This problem should be fixed, can you confirm ?

**Comment by WooAf** [comment]
You're right, will find a way to fix this tomorrow going to bed now
