### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Regerta** [WooAf/PoGoBoT#12]
I want you to add some features if you can
- Pokemon To Transfer List
- Pokemon Not To Transfer List
- Pokemon To Evolve List
- Pokemon Not To Catch List
- Amount of item to keep _(ItemPokeBall, ItemGreatBall, ItemUltraBall, ItemPotion, ItemRevive, etc)_ 
- KeepMinDuplicatePokemon
- Make we can edit the time limit _( that 10 seconds after catching pokemon)_
- Save last coordinates

--
Thank you,
Sorry for my bad english, cuz english is not my primary language

**Comment by WooAf** [comment]
This will be added today

**Comment by Regerta** [comment]
Btw, dont forget to add auto egg hatching too :)
thank you.
