### ISSUE TITLE
Can't login using google

### ISSUE THREAD

**Issue by TAiS46** [WooAf/PoGoBoT#14]
![bildschirmfoto 2016-07-28 um 12 35 11](https://cloud.githubusercontent.com/assets/1446685/17209891/c1e4710a-54bf-11e6-8bd8-b2d7ba65757a.png)

**Comment by LeagueRaINi** [comment]
The Ferox api Key is the Problem, should be fixed soon

**Comment by WooAf** [comment]
Google auth should be fixed
