### ISSUE TITLE
Null Reference - Restarting

### ISSUE THREAD

**Issue by jornschra** [WooAf/PoGoBoT#22]
Hi, using v4.04 im getting an endless loop of:

Null Refference - Restarting
Login type: Google
Null Refference - Restarting
Login type: Google
Null Refference - Restarting
Login type: Google

**Comment by WooAf** [comment]
Press on Advanced Settings and put your username/password

**Comment by jornschra** [comment]
I have always been putting that there. Also sometimes it only goes to pokestops and doesnt see any pokemon ( checkbox is ticked)

**Comment by msumbudy** [comment]
i find that it works for about 10-15 pokestops and immediately goes to null reference - restarting as well

**Comment by jornschra** [comment]
Yep. The bot itself is imo the best one out there.

yesterday i had hours of botting which went superfine, but like msumbudy says it goes to:

23:20:34 PM] Login Type: Google
[23:22:07 PM] System.NullReferenceException: Object reference not set to an instance of an object.
   at PokemonGo.RocketAPI.Window.MainForm.<Execute>d__33.MoveNext() in C:\Users\WooAf\Desktop\PoGoBoT\PokemonGo\RocketAPI\Window\MainForm.cs:line 297

after like 15 pokestops.

keep up the good work

**Comment by Finnx** [comment]
Download the new update, then its working

**Comment by ericseb** [comment]
I notice this issue, its probably because your pokemon/item bag is full. Try emptying some space and try again
