### ISSUE TITLE
No map image:

### ISSUE THREAD

**Issue by isrever** [WooAf/PoGoBoT#24]
when viewing both maps in bot. i get the message 
"Exception: The request was aborted: The opeartion has timed out" + We are sorry, but wee don't have imagery at this zoom level for this region."
p.s. This happens at all zoom levels
p.s. also get this in console:
[15:52:26 PM] Latitude: -36.714359
[15:52:26 PM] Longitude: 174.747205
[15:52:45 PM] Unable to get Country/Place
Thanks

**Comment by WooAf** [comment]
Should be fixed
