### ISSUE TITLE
lucky egg and incense

### ISSUE THREAD

**Issue by Lokiro67** [WooAf/PoGoBoT#28]
the option dont work 

Unhandled exception in using lucky egg: System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à PokemonGo.RocketAPI.Window.MainForm.<btnLuckyEgg_Click>d__60.MoveNext() dans C:\Users\WooAf\Desktop\PoGoBoT\PokemonGo\RocketAPI\Window\MainForm.cs:ligne 1249

Unhandled exception in using Incense: System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à PokemonGo.RocketAPI.Window.MainForm.<btnuseincense_Click>d__61.MoveNext() dans C:\Users\WooAf\Desktop\PoGoBoT\PokemonGo\RocketAPI\Window\MainForm.cs:ligne 1285

**Comment by Finnx** [comment]
Download the new update

**Comment by Lokiro67** [comment]
the error it in the new version
