### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by Guilouz** [WooAf/PoGoBoT#35]
Everything works fine but suddenly impossible to login. I have this and nothing happens.

[22:07:29 PM] Login Type: Google
[22:07:31 PM] System URI Format Exception - Restarting
[22:07:31 PM] Login Type: Google

Login with App working.

**Comment by whyme1234** [comment]
I'm facing the same problem. please help ASAP.

**Comment by ericseb** [comment]
Same thing here.. Also cant login after trying with ptc account. When i use my phonepokemon go  app seems like my account got softbanned

**Comment by ericseb** [comment]
Cant force unban bcos cant login ><

**Comment by whyme1234** [comment]
PHONE POKEMON GO IS WORKING. ERICSEB TRY REBOOTING YOUR PHONE AND THEN LOGIN

**Comment by ericseb** [comment]
Hmm still not working..softban mode

**Comment by leoderenoir** [comment]
Work but dont detect pokestop. "no pokestop to visit here"

**Comment by ericseb** [comment]
Oh yeah to add to that 

The map shows redzone for the pokestops location, thats right before login problem occur

**Comment by ericseb** [comment]
"Please start the bot and wait for map to load before trying to foce unban"

**Comment by leoderenoir** [comment]
someone to help ? I need to play, thx

**Comment by Guilouz** [comment]
Login is now ok after many hours but Pokestop are not detected :

[01:11:16 AM] No PokeStops to visit here, please stop the bot and change your location.
[01:11:16 AM] No nearby useful locations found. Please wait 10 seconds.

**Comment by msumbudy** [comment]
wait for a new update, be patient

**Comment by mahdouch25** [comment]
lol same here :p we all waiting >.<
