### ISSUE TITLE
Pokemon Stops aren't able to be located.

### ISSUE THREAD

**Issue by Gameblank** [WooAf/PoGoBoT#36]
I'm playing and it can't locate pokemon go stops any solutions? ty.

**Comment by orangesuave** [comment]
Because the API changed.  Turn off your bot for now.  Wait for an updated
release.

**Comment by Guilouz** [comment]
Yes same here.

**Comment by ImTxzzy** [comment]
Anyone have any clue when the new update will be released?

**Comment by Nep0** [comment]
Nope, we just need to wait! :+1:

**Comment by Pokemanes** [comment]
FUN FUN FUN FUN, FUN FUN FUN FUN

**Comment by ImTxzzy** [comment]
so what level are you guys?

**Comment by Pokemanes** [comment]
only 18

**Comment by Pokemanes** [comment]
i used the PoGo only yesterday

**Comment by Pokemanes** [comment]
Does Anyone have their discord

**Comment by zimply** [comment]
Has anyone caught a rare pokemon with this? I havent 😢

**Comment by ericseb** [comment]
How rare are you talking about? I caught tauros in central park ny in like the first 30 minutes i start using this :)

**Comment by CrazyClowns** [comment]
Same problem for me and @Pokemanes i have discord
