### ISSUE TITLE
location bug

### ISSUE THREAD

**Issue by Lokiro67** [WooAf/PoGoBoT#37]
the bot cannot start say all time 

No PokeStops to visit here, please stop the bot and change your location.
No nearby useful locations found. Please wait 10 seconds.

but i have changed the location in the setting but dont work

**Comment by Gameblank** [comment]
It's due to the fact that their are API changes please wait for update.

**Comment by tekios21** [comment]
the bot cannot start say all time

No PokeStops to visit here, please stop the bot and change your location.
No nearby useful locations found. Please wait 10 seconds.

but i have changed the location in the setting but dont work i have the same problem :(

**Comment by ericseb** [comment]
Its like that for everyone so JUST WAIT

**Comment by leoderenoir** [comment]
a clu ? one day 2 day ? few hours ?

**Comment by FastFrench** [comment]
If you're in a hurry, then better learn Arm assembly and help 'em to uncrypt the infamous new data.
