### ISSUE TITLE
Not getting inventory maxspace

### ISSUE THREAD

**Issue by poiuytrezaur** [WooAf/PoGoBoT#5]
The bot is always saying max inventory spaces to 350 no matter how many inventory expanders bought

**Comment by WooAf** [comment]
Forgot about this, will fix that

**Comment by poiuytrezaur** [comment]
Also don't get why the bot can't start if inventory is full (it will just get no item from pokestops)

**Comment by WooAf** [comment]
Just a simple protection, we never know what niantic will add to detect bot.
