### ISSUE TITLE
MyPokemon list FLICKERS*while loading pokemon

### ISSUE THREAD

**Issue by septemus** [WooAf/PoGoBoT#7]
It FLICKERS* the visible Pokemon. http://i.imgur.com/hEgZsHn.png

Would it be possible to just append the Pokemon as it finds them, rather than refresh the whole list? Also maybe a multi-transfer function (ctrl+clicking selects multiple but only transfers the first one).

**Comment by WooAf** [comment]
What do you mean it flash ? do you mean when it load ?

**Comment by septemus** [comment]
Yes. I'm in the process of (figuring out how to) record a GIF so I can show you what I mean.

**Comment by septemus** [comment]
Here's a GIF. I hope it adequately describes my issue. If not, I can record my entire screen instead of in the low-FPS GIF.

**Comment by septemus** [comment]
http://i.imgur.com/lLS3ZTD.gifv

**Comment by septemus** [comment]
Wrong buttons. But I hope that GIF conveys my message.

**Comment by WooAf** [comment]
Yeah that's normal it load one pokemonid by one
