### ISSUE TITLE
Razzberry will not recycle

### ISSUE THREAD

**Issue by TAiS46** [WooAf/PoGoBoT#8]
Am I the only one? I think that the razzberry will not be recycle

**Comment by poiuytrezaur** [comment]
Same.

**Comment by TAiS46** [comment]
https://github.com/WooAf/PoGoBoT/blob/6c6ba00cdc0b6a1e4e7772052a0a859177567109/PokemonGo.RocketAPI.GUI/Settings.cs#L65

There is set to keep 200 of berries

**Comment by WooAf** [comment]
Should be fixed
